### PR TITLE
list added

### PR DESCRIPTION
**Pull request by omotenashicoin-project**
We have added our coin to the list. Please merge it into your repository.

### CODE REVIEW

**Comment by junderw** [comment]
did you run the update script?

**Comment by omotenashicoin-project** [comment]
yes.

$  npm run update
> bip44-constants@8.0.2 update /home/ubuntu/coins/bip44-constants
> node update.js > index.js

**Comment by omotenashicoin-project** [comment]
Is this procedure correct?

**Review by junderw — APPROVED** [review]
utACK

**Comment by omotenashicoin-project** [comment]
I'm sorry. 
After executing the update command, 
I forgot to commit the updated index.js.

**Review by junderw — CHANGES_REQUESTED** [review]
You have not been added to SLIP-44

Add yourself to the SLIP-44 list and once it is merged to master on their repo, we can merge this.

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by omotenashicoin-project** [comment]
My coin has already been SLIP-44 merged No.341. Please confirm that it has been added.

**Comment by junderw** [comment]
Your pull request: 513
`[ 0x80000201, "MTNS", "OmotenashiCoin" ],`

SLIP-44: 341
`0x80000155 | MTNS | OmotenashiCoin`

**Comment by junderw** [comment]
Merged in #38 
v8.0.4

**Comment by omotenashicoin-project** [comment]
I changed from No. 513 to No. 341.
The current state is correct.
Thank you very much.

**Pull request closed without merging**
