### PR TITLE
Convert library into 2d Array

### PR DESCRIPTION
**Pull request by junderw**
Mentioned by @jprichardson 

Changed README to reflect it.

### CODE REVIEW

**Comment by jprichardson** [comment]
Thank you. 

1. Can we remove the empty elements? 
2. Any reason we should keep the index as the first element?

**Comment by junderw** [comment]
1. Yes.
2. Not really.......... in fact, it's merely reflecting the constant minus 0x80000000... so it is redundant.

**Comment by junderw** [comment]
1. Removed index from each row
2. Removed rows where both symbol and name are empty strings

This is a major release. So I'll add changelog and version up to this PR.

**Comment by junderw** [comment]
OK, if everything looks good, I'll go ahead a push the tag and publish.

**Comment by junderw** [comment]
Fixes #29 

Well... kinda...

**Comment by fanatid** [comment]
LGTM if works, hope that this solve all our issues with same symbols :)
thanks @junderw !

**Pull request merged**
