### PR TITLE
Updating from SLIP

### LINKED ISSUE #21: X42 invalid character
Encounter this issue with X42, @fanatid do you know what can be wrong with it ?.

Chrome console
screenshot 2018-09-18 16 06 39

VSC
screenshot 2018-09-18 12 10 05

### PR DESCRIPTION
**Pull request by corymsmith**
Ran the update script, needed to fix #21

### CODE REVIEW

**Comment by kolya182** [comment]
@fanatid Can you merge this one, please.

**Comment by fanatid** [comment]
Sorry for delay, I cherry-picked and removed some changes for patch release instead major.

**Comment by kolya182** [comment]
Thanks Kiril, i will wait for npm update.

**Comment by fanatid** [comment]
You already can download 5.2.1 :)

**Pull request closed without merging**
