### PR TITLE
Updating coins

### PR DESCRIPTION
**Pull request by karelbilek**

### CODE REVIEW

**Comment by dcousens** [comment]
LGTM,  no idea where the constants came from.
Do we need a source?

**Comment by fanatid** [comment]
@dcousens updating PR is generated by https://github.com/bitcoinjs/bip44-constants/blob/master/update.sh
maybe we should automate this? 😆

**Comment by dcousens** [comment]
The TRAVIS build is also trying to run `ruby`,  we need a `.travis.yml`

**Review by dcousens — APPROVED** [review]

**Comment by fanatid** [comment]
@jprichardson publish please :)

**Pull request merged**
