### PR TITLE
Latest constants

### PR DESCRIPTION
**Pull request by kolya182**
Fixes https://github.com/bitcoinjs/bip44-constants/pull/17 https://github.com/bitcoinjs/bip44-constants/pull/18

### CODE REVIEW

**Comment by fanatid** [comment]
Thanks, do you need only BTR and X42?

**Comment by kolya182** [comment]
We will need both.

**Comment by fanatid** [comment]
@kolya182 if you need only this two, I propose change only them. Currently slip-44 contains coins with same symbols (BCO = BitcoinOre / Bridgecoin) and some coin change their bip44 value.

**Comment by kolya182** [comment]
@fanatid What if i remove `BCO` from this PR so we don't have duplicates in the list ?. And second question, how do you suggest to handle duplicates ?.

**Comment by fanatid** [comment]
If PR will not change current values I'm going merge and publish it ASAP

**Comment by kolya182** [comment]
Looks good now ?

**Comment by fanatid** [comment]
@kolya182 is this will looks for you? https://github.com/bitcoinjs/bip44-constants/commit/6babbb1974202f30d65b16cc70c338dabdbe0c4b

**Comment by kolya182** [comment]
@fanatid Yes

**Comment by fanatid** [comment]
Sorry for delay, new constants published in 5.2.0

**Comment by kolya182** [comment]
@fanatid Спасибо. I think we can close these https://github.com/bitcoinjs/bip44-constants/pulls ?

**Comment by fanatid** [comment]
Closed.

**Pull request closed without merging**
