### PR TITLE
Fix duplicates problem

### LINKED ISSUE #29: Coins with same symbols
Accordingly to https://github.com/satoshilabs/slips/blob/master/slip-0044.md  there are two coins with same `LBTC` symbol but different `coind`. In such a case we have just one `LBTC`https://github.com/bitcoinjs/bip44-constants/blob/6e9d208a825cffbb5603dbd059fa1179d7a9170c/index.js#L196 How we should handle duplicate symbols ?.

### PR DESCRIPTION
**Pull request by junderw**
Fixes #29 

However, this is a breaking change...

Though to be honest, anyone using LBTC for Lightning Bitcoin already had a breaking change when we overwrote it with Liquid...

I am open to other ways to fix this.

### CODE REVIEW

**Comment by kolya182** [comment]
How about include only symbols from `slip44` (as far as @prusnak [hesitate to add duplicates to the list](https://github.com/satoshilabs/slips/issues/265)) and bump repo version to v8. Whoever needs to use LiteBitcoin (LBTC) or Lightning Bitcoin (LBTC) stay on v7.

**Comment by jprichardson** [comment]
NACK. 

This should be a dumb library that exports and mirrors the SLIP44 table in a simple consumable format like an object or an array. Applications can then deal with the indexing / preference on duplicates.

I think the ideal change is to stop using an object as a map and move to an array of arrays

Example:

```js
[
  [0x80000000, 'BTC', 'Bitcoin', 'https://bitcoin.org/en/'],
  [0x80000001, '', 'Testnet (allcoins)'],
  [0x80000002, 'LTC', 'Litecoin', 'https://litecoin.org/']
  // ...
]
```

Thoughts?

**Comment by kolya182** [comment]
If duplicate symbols prohibited in slip44 than we should not have them here, just mirror whatever in slip44 ?.

**Comment by junderw** [comment]
I would be down for 2d array.

However, we should probably make some warnings on the README to be careful for duplicates and give an example of how we might select the constant...

ie.

```javascript
const bip44Constants = require('bip44-constants')
// When selecting a constant, use a filter on the second element
const myCoin = bip44Constants.filter(item => item[1] === 'MYC')
// ---- OR filter on multiple elements if you are aware of duplicates
const myCoin = bip44Constants.filter(item => item[1] === 'MYC' && item[2] === 'MyCoin')
// Be sure to check for duplicates
assert(myCoin.length === 1)
const myCoinConstant = myCoin[0][0]
```

Actually, as I was writing that... I realized that if the consumer has to constantly be aware of duplicates and fine grain their filter to be specific to their coin, it makes much more sense to just copy the constant into their app hardcoded and the value proposition of this library is pretty much gone.

**Comment by junderw** [comment]
Perhaps:

1. Get SLIP44 to enforce no dupes.

OR

This package really has no meaning anymore... no one can rely on dynamically entering a ticker symbol and getting the proper index without needing to check.

**Comment by junderw** [comment]
Not that I want to merge this anymore, but I found a problem with this Pull Request.

Currently the numbering added to each key of the object is based on the order that they appear in the list, so If I look up LBTC and find my coin to be LBTC_0, if a new LBTC is added to a number previous to the one I used, it will become LBTC_0 and my coin will be bumped to LBTC_1.

More reason to switch to a 2d array if we want to keep this repo and give it any meaning...

I will work on a 2d array solution.

**Pull request closed without merging**
