### PR TITLE
Update constants

### PR DESCRIPTION
**Pull request by topynate**
Generated by update.sh

### CODE REVIEW

**Comment by fanatid** [comment]
Thanks. Published as `4.0.0`, because name was changed
https://github.com/satoshilabs/slips/pull/110
https://github.com/satoshilabs/slips/pull/122

**Comment by dcousens** [comment]
@fanatid couldn't we just have had both?

**Comment by fanatid** [comment]
you right, I could do alias (at least while new coin under name `Link` is not come 😆 ), but already published major bump =(

**Comment by dcousens** [comment]
Less than 24 hours... unpublish go go go!

**Comment by fanatid** [comment]
> Less than 24 hours... unpublish go go go!

Want to be sure on 100%, so we:
- unpublish 4.0.0
- update with alias
- publish minor release 3.x

@dcousens right?

**Comment by dcousens** [comment]
ACK

**Comment by fanatid** [comment]
Done, republished as 3.1.0
https://github.com/bitcoinjs/bip44-constants/commit/a9778f40bfa0c904128cec8ed4f783f2bb12560c

**Comment by jprichardson** [comment]
Way too much work for little gain IMHO. 🙃

**Pull request merged**
