### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by kolya182**
The latest changes and incorporates https://github.com/bitcoinjs/bip44-constants/pull/26, https://github.com/bitcoinjs/bip44-constants/pull/25

### CODE REVIEW

**Comment by fanatid** [comment]
Thanks for update @kolya182 
do you know, when NRG was changed?

**Comment by kolya182** [comment]
@fanatid  https://github.com/satoshilabs/slips/commit/4097e56b801ff908bf93f4086c520b57406e11d0

**Comment by fanatid** [comment]
Waiting https://github.com/satoshilabs/slips/pull/332 now

**Comment by fanatid** [comment]
Published in 7.0.0

**Pull request closed without merging**
