### PR TITLE
remove parseInt requirement

### PR DESCRIPTION
**Pull request by dcousens**
Can still be reviewed manually,  as the hex codes are still in use.

It additionally sorts the list for easy lookup.
The number of constants appears to have grown by 10,  by means of the infrequent update...

### CODE REVIEW

**Comment by dcousens** [comment]
Will need major bump

**Review by fanatid — APPROVED** [review]

**Comment by dcousens** [comment]
@fanatid I can't publish :P

**Comment by fanatid** [comment]
Are you sure? Check again :))

**Comment by fanatid** [comment]
argh, please fix example in README.md first

**Comment by dcousens** [comment]
On it

**Comment by dcousens** [comment]
Updated README in https://github.com/bitcoinjs/bip44-constants/commit/b4d0865de2a9f5b7c5bbc5f9be18ebf96648831d

Published as `4.0.1`

**Comment by dcousens** [comment]
Added CHANGELOG entry in https://github.com/bitcoinjs/bip44-constants/commit/6eb0c9fdc4a153b06a0bf48f7992e947cf76f623

**Pull request merged**
