### PR TITLE
[trivial] package.json files, npm badge

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by jprichardson** [comment]
Thanks. I don't see in any of the commits actually renaming `update.sh` to `update.js` (this only fixes undeclared var: https://github.com/bitcoinjs/bip44-constants/pull/2/commits/e3c8eb9f933111bc00a72da8b0efb1f57a0b457b), furthermore, even if you did, why? It's not technically JavaScript since it has the shebang at the top.

**Comment by fanatid** [comment]
because `Atom` don't highlight js code automatically when I open `update.sh` :)

**Comment by jprichardson** [comment]
> because Atom don't highlight js code automatically when I open update.sh :)

Weird, it should. It does for me. I wonder if I have a plugin or something...

**Comment by fanatid** [comment]
Updated. Commit with renaming was removed. (undeclared var was fixed in other commit)

**Comment by dcousens** [comment]
:+1: 
Looks like you covered all the nits, agreed it isn't js, so renaming was odd.

**Pull request merged**
