### PR TITLE
Sanity checks

### PR DESCRIPTION
**Pull request by junderw**

### CODE REVIEW

**Comment by fanatid** [comment]
This related with https://github.com/bitcoinjs/bip44-constants/issues/21 right?

**Comment by jprichardson** [comment]
NACK on the command line option. It feels like an over-optimization for something we're quite certain should just happen. The rest is great though - thank you.

**Comment by junderw** [comment]
Fixed up a bit:

1. I purposefully messed up some inputs and have confirmed that the suggested command `./update.sh > index.js` will not produce the error text into the js, and the stderr text will show up on the terminal instead (so users will be aware that a certain coin was skipped due to constant formatting error.
2. I first replace all non-relevant characters with ? to make characters more visible on the terminal (since the problem last time was with ZERO-WIDTH-SPACE which will not show up on a terminal)

**Comment by dcousens** [comment]
Is 
``` js
const value = $(col[1]).text().trim()

if (! /^0x[a-fA-F0-9]{8}$/.test(value)) throw ...
```

Not enough?

**Pull request merged**
